return {
    family = [[FiraCode Nerd Font]],
    weight = [[Thin]],
    assume_emoji_presentation = false,
    harfbuzz_features = {
        "calt=1",
        "clig=1",
        "liga=1",
        "cv01",
        "cv02",
        "cv06",
        "zero",
        "onum",
        "cv17",
        "ss05",
        "ss03",
        "cv16",
        "cv31",
        "cv29",
        "cv30",
    },
}
